# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-13 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64, null=True)),
                ('name_zh_hans', models.CharField(max_length=64, null=True)),
                ('name_zh_hant', models.CharField(max_length=64, null=True)),
                ('desc', models.TextField()),
                ('desc_en', models.TextField(null=True)),
                ('desc_zh_hans', models.TextField(null=True)),
                ('desc_zh_hant', models.TextField(null=True)),
                ('dob', models.DateField(verbose_name='Date of birth')),
            ],
        ),
    ]
