# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_centers', '0002_auto_20180416_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationcenter',
            name='net',
            field=models.FloatField(default=0.0),
        ),
    ]
