# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-17 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_centers', '0003_operationcenter_net'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationcenter',
            old_name='net',
            new_name='profit',
        ),
    ]
