# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_centers', '0004_auto_20180417_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationcenter',
            name='name',
            field=models.CharField(max_length=64, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='operationcenter',
            name='name_en',
            field=models.CharField(max_length=64, null=True, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='operationcenter',
            name='name_zh_hans',
            field=models.CharField(max_length=64, null=True, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='operationcenter',
            name='name_zh_hant',
            field=models.CharField(max_length=64, null=True, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='operationcenter',
            name='profit',
            field=models.FloatField(default=0.0, verbose_name='\u5229\u6f64'),
        ),
    ]
