# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profits', '0002_auto_20180418_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profit',
            options={'verbose_name': '\u5229\u6f64', 'verbose_name_plural': '\u5229\u6f64'},
        ),
    ]
