# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_operation_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='operation_center',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation_centers.OperationCenter'),
        ),
    ]
