# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-15 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180415_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='symbol',
            field=models.CharField(default='GLD', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('B', 'BUY'), ('S', 'SELL')], default='B', max_length=2),
        ),
    ]
