# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180415_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('B', 'BUY'), ('S', 'SELL')], default='B', max_length=2, verbose_name='\u4ea4\u6613\u985e\u578b'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(verbose_name='\u50f9\u683c'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(verbose_name='\u6578\u91cf'),
        ),
        migrations.AlterField(
            model_name='order',
            name='symbol',
            field=models.CharField(default='GLD', max_length=32, verbose_name='\u7b26\u865f'),
        ),
    ]
