# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180418_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('B', 'BUY'), ('S', 'SELL')], default='B', max_length=2, verbose_name='order type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='symbol',
            field=models.CharField(default='GLD', max_length=32, verbose_name='symbol'),
        ),
    ]
